import { writeFile } from 'node:fs/promises';
import { QAgent, evaluate, VALIDATION_SEEDS, CONFIG } from '../src/rl.mjs';
const agent = new QAgent(42),
  curve = [];
let rewards = [];
for (let ep = 0; ep < 1200; ep++) {
  const point = agent.trainEpisode(ep, 1200);
  rewards.push(point.reward);
  if ((ep + 1) % 25 === 0) {
    curve.push({
      ...point,
      reward: rewards.reduce((a, b) => a + b, 0) / rewards.length,
      validation: -evaluate(agent, VALIDATION_SEEDS).learned,
    });
    rewards = [];
  }
}
await writeFile(
  new URL('../src/reference.json', import.meta.url),
  JSON.stringify({
    provenance:
      'Actual Q-learning run generated by scripts/reference.mjs; synthetic environment',
    algorithm: 'tabular Q-learning',
    seed: 42,
    episodes: 1200,
    config: CONFIG,
    q: Array.from(agent.q),
    curve,
    evaluation: evaluate(agent),
  })
);
